image: gitlab-registry.cern.ch/lhcb-docker/analysis-ci/cc7:latest

stages:
   - build
   - test

before_script:
   - apt-get update && apt-get install clang-format -y
   - source /cvmfs/sft.cern.ch/lcg/views/setupViews.sh LCG_99 x86_64-centos7-gcc10-opt

build:
   stage: build
   script:
      - mkdir build
      - cd build
      - cmake ../ -DINSTALL_TESTS=ON
      - make install
   artifacts:
      paths:
         - build/

test:
   stage: test
   script:
      - ./build/test/cpp/test
      - ./build/test/cpp/test_earth
   dependencies:
      - build

cmake:
   stage: test
   script:
      - mkdir test/cmake/build
      - cd test/cmake/build
      - CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:../../../build cmake ../
      - make
      - ./main
   dependencies:
      - build

format:
   stage: test
   script:
      - clang-format --dry-run -Werror $(find . \( -name "*.cpp" -or -name "*.hpp" \) -and -not -path "*build*")
