image: gitlab-registry.cern.ch/lhcb-docker/analysis-ci/cc7:latest

stages:
   - build
   - test

before_script:
   - source /cvmfs/sft.cern.ch/lcg/views/setupViews.sh LCG_100 x86_64-centos7-gcc10-opt

build:
   stage: build
   script:
      - mkdir build
      - cd build
      - cmake ../ -DINSTALL_EXAMPLES=ON -DINSTALL_TESTS=ON
      - make install
   artifacts:
      paths:
         - build/

test:
   stage: test
   script:
      - ./build/test/cpp/test_core
      - ./build/test/cpp/test_containers
      - ./build/test/cpp/test_world
   needs:
      - job: build
        artifacts: true

examples:
   stage: test
   script:
      - ./build/examples/earth_and_moon
      - ./build/examples/solar_system
   needs:
      - job: build
        artifacts: true

cmake:
   stage: test
   script:
      - mkdir test/cmake/build
      - cd test/cmake/build
      - CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:../../../build cmake ../
      - make
      - ./main
   needs:
      - job: build
        artifacts: true

format:
   stage: test
   image: ubuntu:20.04
   before_script:
      - apt-get update && apt-get install -y clang-format
   script:
      - clang-format --dry-run -Werror $(find . \( -name "*.cpp" -or -name "*.hpp" \) -and -not -path "*build*")
