dist: focal
language: python

os: linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - cmake
env:
- CC=gcc-7 CXX=g++-7

#branches:
#  only:
#  - master

before_install:
- ${CC} --version
- ${CXX} --version
- cmake --version
- sudo apt-get install clang-format
- clang-format --version

install:
- mkdir build
- cd build
- cmake ../ -DINSTALL_EXAMPLES=ON -DINSTALL_TESTS=ON -DCMAKE_CXX_COMPILER=${CXX}
- make install
- cd ..

jobs:
  include:
  - name: cpp
    script:
    - ./build/test/cpp/test_core
    - ./build/test/cpp/test_containers
    - ./build/test/cpp/test_world
    after_success: " "
  - name: examples
    script:
    - ./build/examples/earth_and_moon
    - ./build/examples/solar_system
    - ./build/examples/star_formation
  - name: cmake
    script:
    - mkdir test/cmake/build
    - cd test/cmake/build
    - CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:../../../build cmake ../
    - make
    - ./main
  - name: format
    python: 3.7
    install: " "
    script:
    - clang-format --dry-run -Werror $(find . \( -name "*.cpp" -or -name "*.hpp" \) -and -not -path "*build*")
